name: Deploy Subnext

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest Subnext code
        uses: actions/checkout@v4

      - name: Deploy to GO54
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/.env
            **/.env.*
            !**/.env.example
            **/uploads/**
            **/*.sql
            **/*.zip
